# ESCREVA UM PROGRAMA QUE PERGUNTE A QUAMTIDADE DE KM PERCORRIDO POR UM CARRO ALUGADO E A QUANTIDADE DE DIAS PELOS QUAIS ELE FOI ALUGADO.
# CALCULE O PREÇO A PAGAR, SABENDO QUE O CARRO CUSTA R$ 60 POR DIA E R$0,15 POR KM RODADO.

KM = float(input(" QUANTOS KM VC RODOU? "))
DIA = int(input("QUANTOS DAIS VC FICOU COM O CARRO? "))

CAL_KM = (KM * 0.15) + (DIA * 60)

print("O CARRO FOI ALUGADO POR {} DIAS \nRODOU {} KM  \nO VALOR TOTAL A PAGAR R$ {:.2f}".format(DIA, KM, CAL_KM))




